# frontend/nginx-frontend.conf
server {
    listen 80;
    server_name _; # Escucha en cualquier hostname que le llegue (el proxy Nginx principal se encarga del hostname real)

    # Raíz donde están los archivos estáticos de React (después del build)
    root /usr/share/nginx/html;
    index index.html index.htm; # Archivo por defecto a servir

    location / {
        # Intenta servir el archivo solicitado directamente ($uri)
        # Si es un directorio, intenta servir el index.html de ese directorio ($uri/)
        # Si ninguno de los anteriores existe, SIRVE EL /index.html PRINCIPAL.
        # Esto es crucial para que React Router maneje el enrutamiento.
        try_files $uri $uri/ /index.html;
    }

    # Opcional: Configuración para cachear estáticos (JS, CSS, imágenes)
    # location ~* \.(?:css|js|jpg|jpeg|gif|png|ico|webp|svg|woff|woff2|ttf|eot)$ {
    #     expires 1y;
    #     access_log off;
    #     add_header Cache-Control "public";
    # }

    # Opcional: Deshabilitar logs de acceso para todo si no los necesitas en este Nginx
    # access_log off;
}